### PR TITLE
Change from ATF to OMB content

### PR DESCRIPTION
**Pull request by theresaanna**
Changes the content of the README from ATF to OMB-specific. Removes Gemnasium temporarily as I am unable to configure the project due to our Github org breaking the Gemnasium site.

### CODE REVIEW

**Comment by theresaanna** [comment]
Need to get Travis passing

**Comment by theresaanna** [comment]
And now Travis is passing! Though we will want to remove my temporary script command as soon as we have something to run.

**Comment by stvnrlly** [comment]
I stumbled into this PR somehow and saw the Gemnasium thing. Until that gets figured out, you can still activate the project with some jQuery: `$('[name=submit_github_projects]').before('<input type="hidden" name="full_names[]" value="org/repo-name" />').click()`.

(via https://gsa-tts.slack.com/archives/infrastructure/p1484672271001423)

**Comment by jipiboily** [comment]
Hey, JP from Gemnasium here. Did you contact our support @theresaanna? We're always happy to help 😀

**Comment by cmc333333** [comment]
Hey there @stvnrlly, we did indeed add the project through the JS work around. @jipiboily, I believe 18F's already contacted your support group (search for messages from @NoahKunin) -- effectively, we have too many repositories in our Github org.

In any event, the work around works! Thanks @theresaanna !

**Comment by afeld** [comment]
@jipiboily We wrote up some workarounds in https://github.com/18F/before-you-ship/issues/248 - would love input there!

**Comment by jipiboily** [comment]
@afeld sorry for the delay here. Someone's going to look into it shortly.

**Comment by gonzoyumo** [comment]
Hi there, Olivier from Gemnasium.

There was indeed a support request open by the account owner. At that time the issue was solved with a manual sync to work around the UI timeout.

I just did it again but the 18F org does no longer show up as an accessible org for this Github account.

Can someone open an issue on support.gemnasium.com to follow up and talk about it?

Thanks and nice work around btw ;)

**Comment by NoahKunin** [comment]
@gonzoyumo Ok, done!

http://support.gemnasium.com/forums/236528-general/suggestions/17864956-support-extremely-large-github-organizations

**Comment by gonzoyumo** [comment]
@NoahKunin thanks, we'll try to work on that. Anyway as I mentioned above it won't totally resolve your issue. The associated Github account (@dlapiduz) doesn't have 18F in its orgs list anymore.

Please open a ticket by clicking on "Contact support" on http://support.gemnasium.com so that we can handle that.

**Pull request merged**
